"""Battery metrics for OVMS integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfPower,
    UnitOfSpeed,
    UnitOfTemperature,
)

# Custom unit constants
UNIT_AMPERE_HOUR = "Ah"

# Battery metrics
BATTERY_METRICS = {
    # 12V Battery metrics
    "v.b.12v.current": {
        "name": "12V Battery Current",
        "description": "Auxiliary 12V battery momentary current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "battery",
    },
    "v.b.12v.voltage": {
        "name": "12V Battery Voltage",
        "description": "Auxiliary 12V battery momentary voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.12v.voltage.alert": {
        "name": "12V Battery Voltage Alert",
        "description": "Auxiliary battery under voltage alert",
        "icon": "mdi:alert",
        "category": "battery",
        "device_class": BinarySensorDeviceClass.PROBLEM,
    },
    "v.b.12v.voltage.ref": {
        "name": "12V Battery Reference Voltage",
        "description": "Auxiliary 12V battery reference voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },

    # Main battery cell metrics
    "v.b.c.temp": {
        "name": "Cell Temperatures",
        "description": "Cell temperatures",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.temp.alert": {
        "name": "Cell Temperature Alerts",
        "description": "Cell temperature deviation alert level",
        "icon": "mdi:alert",
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.temp.dev.max": {
        "name": "Max Cell Temperature Deviation",
        "description": "Cell maximum temperature deviation observed",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.temp.max": {
        "name": "Maximum Cell Temperatures",
        "description": "Cell maximum temperatures",
        "icon": "mdi:thermometer-high",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.temp.min": {
        "name": "Minimum Cell Temperatures",
        "description": "Cell minimum temperatures",
        "icon": "mdi:thermometer-low",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.voltage": {
        "name": "Cell Voltages",
        "description": "Cell voltages",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.voltage.alert": {
        "name": "Cell Voltage Alerts",
        "description": "Cell voltage deviation alert level",
        "icon": "mdi:alert",
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.voltage.dev.max": {
        "name": "Max Cell Voltage Deviation",
        "description": "Cell maximum voltage deviation observed",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.voltage.max": {
        "name": "Maximum Cell Voltages",
        "description": "Cell maximum voltages",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
        "has_cell_data": True,
    },
    "v.b.c.voltage.min": {
        "name": "Minimum Cell Voltages",
        "description": "Cell minimum voltages",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
        "has_cell_data": True,
    },

    # Main battery metrics
    "v.b.cac": {
        "name": "Battery Capacity",
        "description": "Calculated battery pack capacity",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UNIT_AMPERE_HOUR,
        "category": "battery",
    },
    "v.b.capacity": {
        "name": "Battery Usable Capacity",
        "description": "Main battery usable capacity",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "v.b.consumption": {
        "name": "Battery Consumption",
        "description": "Main battery momentary consumption",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.WATT_HOUR,
        "category": "battery",
    },
    "v.b.coulomb.recd": {
        "name": "Battery Coulomb Recovered Trip",
        "description": "Main battery coulomb recovered on trip/charge",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UNIT_AMPERE_HOUR,
        "category": "battery",
    },
    "v.b.coulomb.recd.total": {
        "name": "Battery Coulomb Recovered Total",
        "description": "Main battery coulomb recovered total (life time)",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UNIT_AMPERE_HOUR,
        "category": "battery",
    },
    "v.b.coulomb.used": {
        "name": "Battery Coulomb Used Trip",
        "description": "Main battery coulomb used on trip",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UNIT_AMPERE_HOUR,
        "category": "battery",
    },
    "v.b.coulomb.used.total": {
        "name": "Battery Coulomb Used Total",
        "description": "Main battery coulomb used total (life time)",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UNIT_AMPERE_HOUR,
        "category": "battery",
    },
    "v.b.current": {
        "name": "Battery Current",
        "description": "Main battery momentary current (output=positive)",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "battery",
    },
    "v.b.energy.recd": {
        "name": "Battery Energy Recovered Trip",
        "description": "Main battery energy recovered on trip/charge",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "v.b.energy.recd.total": {
        "name": "Battery Energy Recovered Total",
        "description": "Main battery energy recovered total (life time)",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "v.b.energy.used": {
        "name": "Battery Energy Used Trip",
        "description": "Main battery energy used on trip",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "v.b.energy.used.total": {
        "name": "Battery Energy Used Total",
        "description": "Main battery energy used total (life time)",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "v.b.health": {
        "name": "Battery Health Description",
        "description": "General textual description of battery health",
        "icon": "mdi:battery-heart",
        "category": "battery",
    },

    # Battery pack level metrics
    "v.b.p.level.avg": {
        "name": "Cell Level Average",
        "description": "Cell level - pack average",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.p.level.max": {
        "name": "Cell Level Maximum",
        "description": "Cell level - strongest cell in pack",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.p.level.min": {
        "name": "Cell Level Minimum",
        "description": "Cell level - weakest cell in pack",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.p.level.stddev": {
        "name": "Cell Level Deviation",
        "description": "Cell level - pack standard deviation",
        "icon": "mdi:chart-bell-curve",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.p.temp.avg": {
        "name": "Cell Temperature Average",
        "description": "Cell temperature - pack average",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.p.temp.max": {
        "name": "Cell Temperature Maximum",
        "description": "Cell temperature - warmest cell in pack",
        "icon": "mdi:thermometer-high",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.p.temp.min": {
        "name": "Cell Temperature Minimum",
        "description": "Cell temperature - coldest cell in pack",
        "icon": "mdi:thermometer-low",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.p.temp.stddev": {
        "name": "Cell Temperature Deviation",
        "description": "Cell temperature - current standard deviation",
        "icon": "mdi:chart-bell-curve",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.p.temp.stddev.max": {
        "name": "Max Cell Temperature Deviation",
        "description": "Cell temperature - maximum standard deviation observed",
        "icon": "mdi:chart-bell-curve",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.p.voltage.avg": {
        "name": "Cell Voltage Average",
        "description": "Cell voltage - pack average",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.p.voltage.grad": {
        "name": "Cell Voltage Gradient",
        "description": "Cell voltage - gradient of current series",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.p.voltage.max": {
        "name": "Cell Voltage Maximum",
        "description": "Cell voltage - strongest cell in pack",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.p.voltage.min": {
        "name": "Cell Voltage Minimum",
        "description": "Cell voltage - weakest cell in pack",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.p.voltage.stddev": {
        "name": "Cell Voltage Deviation",
        "description": "Cell voltage - current standard deviation",
        "icon": "mdi:chart-bell-curve",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.p.voltage.stddev.max": {
        "name": "Max Cell Voltage Deviation",
        "description": "Cell voltage - maximum standard deviation observed",
        "icon": "mdi:chart-bell-curve",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.b.power": {
        "name": "Battery Power",
        "description": "Main battery momentary power (output=positive)",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "battery",
    },
    "v.b.range.est": {
        "name": "Estimated Range",
        "description": "Estimated range",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "battery",
    },
    "v.b.range.full": {
        "name": "Full Charge Range",
        "description": "Ideal range at 100% SOC & current conditions",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "battery",
    },
    "v.b.range.ideal": {
        "name": "Ideal Range",
        "description": "Ideal range",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "battery",
    },
    "v.b.range.speed": {
        "name": "Range Change Speed",
        "description": "Momentary ideal range gain/loss (charge/discharge) speed",
        "icon": "mdi:speedometer",
        "device_class": SensorDeviceClass.SPEED,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR,
        "category": "battery",
    },
    "v.b.soc": {
        "name": "Battery Level",
        "description": "State of charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.soh": {
        "name": "Battery Health",
        "description": "State of health",
        "icon": "mdi:battery-heart",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "v.b.temp": {
        "name": "Battery Temperature",
        "description": "Main battery momentary temperature",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "battery",
    },
    "v.b.voltage": {
        "name": "Battery Voltage",
        "description": "Main battery momentary voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "v.e.regenbrake": {
        "name": "Regenerative Braking",
        "description": "Regenerative braking active state",
        "icon": "mdi:battery-charging",
        "device_class": BinarySensorDeviceClass.RUNNING,
        "category": "battery",
    },
}
